### ISSUE TITLE
Translation into Czech

### ISSUE THREAD

**Issue by Maca-LSczechforum** [Peppie84/FS22_BeesRevamp#13]
Hi, I translated your mod into Czech. I also discovered my apiary in the text of your mod. (Bee Hive Trailer by Maca)
[translation_cz.txt](https://github.com/user-attachments/files/17562636/translation_cz.txt)

Regards  Maca

**Comment by Peppie84** [comment]
Hi Maca, thanks for your translation. I'll add it for the next release.
