### ISSUE TITLE
Help with Simplified Chinese Translation

### ISSUE THREAD

**Issue by orangestar254** [Peppie84/FS22_BeesRevamp#21]
[translation_cs.zip](https://github.com/user-attachments/files/17793209/translation_cs.zip)

**Comment by orangestar254** [comment]
This is my first attempt to help mod authors with their translations, so please forgive me if I have some problems

**Comment by orangestar254** [comment]
It's great to hear from you

**Comment by Peppie84** [comment]
@orangestar254 why did you close this ticket?

**Comment by orangestar254** [comment]
@Peppie84 Sorry it's my first time using github, there are some rules I don't quite understand,I didn't mean to close the ticket.my bad man
