### ISSUE TITLE
Warning: DensityMapVisualizationOverlay is being reset, because a DensityMap it refers to was deleted.

### ISSUE THREAD

**Issue by FirenzeIT** [Peppie84/FS22_BeesRevamp#6]
Hello @Peppie84, it's possible to fix the warning as a title, in a next update of this mod please?? Without this mod, not have this warning (tried also only with this installed, without any other extra stuff)...

**Comment by Peppie84** [comment]
Hi @FirenzeIT, thanks for your report. This mod does not interact with the `DensityMapVisualizationOverlay` in any case. I just startet a new "Erlengrat" map, with just the BeesRevamp mod and i see no warning message like you.

You can add your log if you want.

**Comment by FirenzeIT** [comment]
Hi, i playing with PF enabled, so probably for this i have the warning.. So, today when i could play, i add here a log with and without PF and this mod, for proof! 😎

**Comment by Peppie84** [comment]
Hi @FirenzeIT , any news for this ticket? Otherwise I would close the ticket.

**Comment by FirenzeIT** [comment]
Hi, yes i have always this type of warning with this mod, and without them the warning is disappeared.. Today i try another yet.. When i done this, i update you soon..

**Comment by Peppie84** [comment]
I don't understand. The Warning is in both logs. With and without BeesRevamp mod. I can not see any relation to BeesRevamp.

**Comment by FirenzeIT** [comment]
Yes, I meant that. It may be the PF or the Production Revamp that makes this warning....

**Comment by Peppie84** [comment]
a ok 😅 so i 'll close this ticket. Thanks
