### ISSUE TITLE
Full ITA's (translation_it)

### ISSUE THREAD

**Issue by FirenzeIT** [Peppie84/FS22_BeesRevamp#7]
Hi @Peppie84, I make and add here, also a full ITA's translation for next update officially on modhub!

[translation_it.txt](https://github.com/user-attachments/files/17217311/translation_it.txt)
[modDesc.txt](https://github.com/user-attachments/files/17217325/modDesc.txt)

**Comment by Peppie84** [comment]
Hi @FirenzeIT , thanks for your translation. This merge will be used in one of the next releases.

**Comment by FirenzeIT** [comment]
> Hi @FirenzeIT , thanks for your translation. This merge will be used in one of the next releases.

Perfectly, thank you too 👍🏻
