### ISSUE TITLE
Support other bee hive mods

### ISSUE THREAD

**Issue by Peppie84** [Peppie84/FS22_BeesRevamp#9]
Request by Sebsch to support more bee hive mods:

https://www.farming-simulator.com/mod.php?mod_id=249920 by Zoli708
![image](https://github.com/user-attachments/assets/3e0a6918-41e3-42c0-8244-382e9f7e86d7)

https://www.farming-simulator.com/mod.php?mod_id=225503 by MefiuFs
![image](https://github.com/user-attachments/assets/e46f7a74-938a-4556-903b-469e01687e5f)

https://www.farming-simulator.com/mod.php?mod_id=243337 by Maca
![image](https://github.com/user-attachments/assets/b8fb6054-7cd3-473f-9a06-54a6977e2ff8)

**Comment by FirenzeIT** [comment]
Hi, please add also this other below bee hive mods:

-) https://www.farming-simulator.com/mod.php?lang=en&country=it&mod_id=277202&title=fs2022 by doodoo

-) https://www.farming-simulator.com/mod.php?lang=en&country=it&mod_id=259091 by 	Ls_Dezign
